# development:
#    adapter: mysql2
#    encoding: utf8
#    database: orca
#    pool: 5
#    username: root
#    password: 
#    socket: /tmp/mysql.sock
#    encoding: utf8
#    collation: utf8_general_ci

development:
    adapter:   mysql2
    database:  orca
    username:  friendmash
    password:  Lik3aG6
    host: friendmash-production.clhyg7sm4xmb.us-east-1.rds.amazonaws.com
    port: 3306

production:
 adapter:   mysql2
 database:  orca
 username:  friendmash
 password:  Lik3aG6
 host: friendmash-production.clhyg7sm4xmb.us-east-1.rds.amazonaws.com
 port: 3306
 
 
#  heroku config:add DATABASE_URL=mysql2://friendmash:Lik3aG6@friendmash-production.clhyg7sm4xmb.us-east-1.rds.amazonaws.com/orca